name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

env:
  lockfile: pnpm-lock.yaml
  node_version: "20"

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        id: pnpm-install

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          registry-url: https://registry.npmjs.org


      - name: Install dependencies
        run: pnpm install

      - name: Build dist
        run: pnpm run build

      - name: Update npm
        run: npm install -g npm@latest
  
      - name: Publish to npm
        id: publish
        run: npm publish --no-git-checks
